project_id = "fipdpcitsjpqivljrktj"

[functions.get-mapbox-token]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true
